import Header from "@/ui/layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				{children}
				<footer>
					<p className="text-center text-sm text-gray-500">
						© 2021 All rights reserved.
					</p>
				</footer>
			</body>
		</html>
	);
}
